### ISSUE TITLE
Unexpected failing test methods [D4J Time-27]

### ISSUE THREAD

**Issue by jose** [Programming-Systems-Lab/vmvm#7] opened 2018-12-22 07:56 UTC
Hi @jon-bell,

First of all let me thank you for releasing this tool as an open-source project.

I've been trying to integrate your tool into [Defects4J](https://github.com/rjust/defects4j) and I've noticed that some test methods started to fail all of the sudden. Long story short, this integration will speed up the traditional test phase out of the box and in the long shot (and with a tiny modification) will allow us to run each test method in an "_independent environment_" without having to start a new process for each test method.

So, for a particular D4J bug (Time-27) I get more failing test methods than unexpected.
I have created a minimal example to reproduce this issue. Please find below the instructions to reproduce the issue.

### Setup

```bash
$ mkdir -p /tmp/vmvm-d4j
$ cd /tmp/vmvm-d4j

# Get Java-7
$ wget http://people.cs.umass.edu/~rjust/defects4j/download/jdk-7u80-linux-x64.tar.gz
$ tar -xzf jdk-7u80-linux-x64.tar.gz
$ export JAVA_HOME=/tmp/vmvm-d4j/jdk1.7.0_80
$ export PATH="$JAVA_HOME/bin:$PATH"

# Get VMVM
$ git clone https://github.com/Programming-Systems-Lab/vmvm.git
```

Because VMVM requires Java-8 and D4J requires Java-7, I made the following change to VMVM:
```diff
diff --git a/vmvm/pom.xml b/vmvm/pom.xml
index d068672..cf38532 100644
--- a/vmvm/pom.xml
+++ b/vmvm/pom.xml
@@ -53,8 +53,8 @@
 				<artifactId>maven-compiler-plugin</artifactId>
 				<version>3.1</version>
 				<configuration>
-					<source>1.8</source>
-					<target>1.8</target>
+					<source>1.7</source>
+					<target>1.7</target>
 				</configuration>
 			</plugin>
 			<plugin>
diff --git a/vmvm/src/main/java/edu/columbia/cs/psl/vmvm/runtime/VMVMClassFileTransformer.java b/vmvm/src/main/java/edu/columbia/cs/psl/vmvm/runtime/VMVMClassFileTransformer.java
index 8fb1ccf..6aad894 100644
--- a/vmvm/src/main/java/edu/columbia/cs/psl/vmvm/runtime/VMVMClassFileTransformer.java
+++ b/vmvm/src/main/java/edu/columbia/cs/psl/vmvm/runtime/VMVMClassFileTransformer.java
@@ -290,9 +290,9 @@ public class VMVMClassFileTransformer implements ClassFileTransformer {
 //		System.out.println("Generating " + newName + " in " + loader);
 
 		if (!isIgnoredClass(cr.getSuperName()))
-			cw.visit(Opcodes.V1_8, Opcodes.ACC_PUBLIC | Opcodes.ACC_INTERFACE | Opcodes.ACC_ABSTRACT, newName, null, cr.getSuperName() + Constants.VMVM_RESET_SUFFIX, null);
+			cw.visit(Opcodes.V1_7, Opcodes.ACC_PUBLIC | Opcodes.ACC_INTERFACE | Opcodes.ACC_ABSTRACT, newName, null, cr.getSuperName() + Constants.VMVM_RESET_SUFFIX, null);
 		else
-			cw.visit(Opcodes.V1_8, Opcodes.ACC_PUBLIC | Opcodes.ACC_INTERFACE | Opcodes.ACC_ABSTRACT, newName, null, "java/lang/Object", null);
+			cw.visit(Opcodes.V1_7, Opcodes.ACC_PUBLIC | Opcodes.ACC_INTERFACE | Opcodes.ACC_ABSTRACT, newName, null, "java/lang/Object", null);
 		cw.visitSource(null, null);
 
 		for (FieldNode fn : cv.getAllFields()) {
```

```bash
# Compile VMVM
$ cd /tmp/vmvm-d4j/vmvm
$ mvn package

# Get D4J
$ cd /tmp/vmvm-d4j
$ git clone https://github.com/rjust/defects4j.git
$ cd defects4j
$ ./init.sh
$ export D4J_HOME=/tmp/vmvm-d4j/defects4j
```

### Time-27

```bash
$ cd /tmp/vmvm-d4j
$ $D4J_HOME/framework/bin/defects4j checkout -p "Time" -v "27b" -w "Time-27b"
$ cd Time-27b
$ $D4J_HOME/framework/bin/defects4j compile
```

Custom made build file `/tmp/vmvm-d4j/Time-27b/vmvm-build.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project name="VMVM-D4J" default="test">

  <target name="test">
    <junit printsummary="yes" haltonfailure="no" haltonerror="no" fork="true" forkmode="${forkmode}" showOutput="true">
      <jvmarg value="-Xbootclasspath/a:${vmvm.jar}"/>
      <jvmarg value="-javaagent:${vmvm.jar}"/>
      <classpath>
        <pathelement path="${classes.dir}" />
        <pathelement path="${test.classes.dir}" />
        <pathelement path="${junit.jar}" />
        <pathelement path="${ant-mvn-formatter.jar}" />
        <pathelement location="${vmvm.jar}" />
      </classpath>

      <formatter type="plain" usefile="false" />
      <formatter classname="edu.columbia.cs.psl.vmvm.AntJUnitTestListener" usefile="false"/>

      <test name="org.joda.time.TestBaseSingleFieldPeriod"/>
      <test name="org.joda.time.TestDays"/>
    </junit>
  </target>

</project>
```

Now, when I run those two test classes defined in the `/tmp/vmvm-d4j/Time-27b/vmvm-build.xml` file with `forkMode="once"` (as described in VMVM's [README](https://github.com/Programming-Systems-Lab/vmvm/blob/vmvm2/README.md)) file:
```bash
$ ant -f vmvm-build.xml \
    -Dclasses.dir=/tmp/vmvm-d4j/Time-27b/build/classes \
    -Dtest.classes.dir=/tmp/vmvm-d4j/Time-27b/build/tests \
    -Djunit.jar=$D4J_HOME/framework/projects/lib/junit-4.11.jar \
    -Dvmvm.jar=/tmp/vmvm-d4j/vmvm/vmvm/target/vmvm-2.0.0-SNAPSHOT.jar \
    -Dant-mvn-formatter.jar=/tmp/vmvm-d4j/vmvm/vmvm-ant-junit-formatter/target/vmvm-ant-junit-formatter-2.0.0-SNAPSHOT.jar \
    -Dforkmode=once
```
I get two failing test methods instead of zero (yes, none of those two test classes reveal the the bug).
However, when I run them with `forkMode="perTest"` (i.e., a new process for each test class), i.e.:
```bash
$ ant -f vmvm-build.xml \
    -Dclasses.dir=/tmp/vmvm-d4j/Time-27b/build/classes \
    -Dtest.classes.dir=/tmp/vmvm-d4j/Time-27b/build/tests \
    -Djunit.jar=$D4J_HOME/framework/projects/lib/junit-4.11.jar \
    -Dvmvm.jar=/tmp/vmvm-d4j/vmvm/vmvm/target/vmvm-2.0.0-SNAPSHOT.jar \
    -Dant-mvn-formatter.jar=/tmp/vmvm-d4j/vmvm/vmvm-ant-junit-formatter/target/vmvm-ant-junit-formatter-2.0.0-SNAPSHOT.jar \
    -Dforkmode=perTest
```
everything goes well, i.e., zero failing test methods.

Any chance you could have a look at this?

--
Thanks,
Jose

**Comment by jon-bell** [comment] 2018-12-23 19:44
Glad to see that there is still some interest in VMVM. 

This codebase is a complete rewrite from the ICSE 2014 version of VMVM, and it seems I might have introduced a regression or two - the ones you were facing are now fixed.

While it might appear to work in some cases to just change the class file version to 7, I believe that it will crash if you encounter an interface with static fields. The ICSE 2014 version of VMVM required a pre-instrumentation step, where you define up-front where all of the class files are, and it analyzes and then instruments them. The technical reason for this was to detect when you were accessing a field of an interface vs a class, because we would have to do some tricks to reset the static fields of interfaces differently from of classes (because you can't define non-static methods in interfaces). In this codebase (vmvm2), this is solved by using default methods in interfaces (not supported in Java 7).

If you are very interested in using VMVM with this project, it might be worthwhile to try to use the old version (still in the `master` branch), which will work fine with Java 7.

**Closed** 2018-12-26 18:37 UTC
